version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: todo-cache
    restart: on-failure
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ../cache-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - backend

  cache-init:
    image: redis/redis-stack:latest
    volumes:
      - ./cache-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    command: /data/load-redis.sh cache
    networks:
      - backend
    depends_on:
      cache:
        condition: service_started
    
    
  voter-api:
    image: md3852/voter-api:v1
    container_name: voter-api 
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      cache-init:
        condition: service_completed_successfully
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend
networks:
  frontend:
    internal: false
  backend:
    internal: false